name: Waka Readme

on:
  schedule:
    # Runs at 12am ACDT (Adelaide during Daylight Saving Time), which is 1:30 PM UTC.
    - cron: '30 13 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_BY_ME: "False"
          COMMIT_USERNAME: "readme-bot"
          COMMIT_EMAIL: "readme-bot@example.com"
          SHOW_OS: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_COMMIT: "False"
          SHOW_TIMEZONE: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          DEBUG_LOGGING: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_UPDATED_DATE: "False"
          SHOW_LOC_CHART: "False"
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: "wakaaddon"
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          SHOW_TITLE: true
