name: Waka Readme Additional Metrics

on:
  schedule:
    - cron: '30 13 * * *'
  workflow_dispatch:

jobs:
  update-readme-additional:
    name: Update Readme with Additional Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: "waka-additional"
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          SHOW_TITLE: true